# Generated by Django 4.2.6 on 2023-10-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_businessproject_liked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy', models.CharField(default='Нет данных', max_length=100)),
                ('full_name', models.CharField(default='Аноним', max_length=100)),
                ('title', models.CharField(default='Без названия', max_length=100)),
                ('description', models.TextField(default='Описание отсутствует')),
                ('city', models.CharField(default='Не указан', max_length=50)),
                ('experience', models.TextField(default='Опыт не указан')),
                ('last_experience', models.TextField(default='Последний опыт не указан')),
                ('about', models.TextField(default='Информация отсутствует')),
                ('phone_number', models.CharField(default='Не указан', max_length=15)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
