# Generated by Django 4.2.6 on 2023-10-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_vacancy_created_at_vacancy_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='face_photo',
            field=models.ImageField(blank=True, null=True, upload_to='face_photos/'),
        ),
    ]
