# Generated by Django 4.2.6 on 2023-10-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0007_alter_vacancy_face_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='face_photo',
            field=models.ImageField(blank=True, null=True, upload_to='face_photos/'),
        ),
    ]
