# Generated by Django 4.2.6 on 2023-10-31 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0008_alter_vacancy_face_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='title',
        ),
    ]
