# Generated by Django 4.2.6 on 2023-10-31 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0009_remove_vacancy_description_remove_vacancy_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField()),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.vacancy')),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='vacancies', to='django_app.review'),
        ),
    ]
