# Generated by Django 4.2.6 on 2023-11-01 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0013_alter_work_publish_date_alter_work_published_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
