# Generated by Django 4.2.7 on 2023-11-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0022_alter_message_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
