# Generated by Django 4.2.7 on 2023-11-21 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0024_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproject',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
